<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>stairs_icon.ico</ApplicationIcon>
    <AssemblyName>TrappeApp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\FCM_logo.png" />
    <None Remove="Images\FCM_logo_og_agf.png" />
    <None Remove="Images\img_femdesign.png" />
    <None Remove="Images\img_home.png" />
    <None Remove="Images\img_projektering.png" />
    <None Remove="Images\img_testpage.png" />
    <None Remove="Images\minimize_def.png" />
    <None Remove="Images\minimize_mo.png" />
    <None Remove="Images\shutdown_def.png" />
    <None Remove="Images\shutdown_mo.png" />
    <None Remove="Model\cfg_Agressiv.xml" />
    <None Remove="Model\cfg_EkstraAgressiv.xml" />
    <None Remove="Model\cfg_Standard.xml" />
    <None Remove="Model\FEM-Design tab\Doc_template_NoSnowLoad.dsc" />
    <None Remove="Model\FEM-Design tab\Doc_template_SnowLoad.dsc" />
    <None Remove="Model\Projektering tab\Beregningsark\Gelænder Type A med balusterben _v 1.0_2023_rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Gelænder Type A uden ben _v_ 1.0_2023_rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Gelænder Type A v 1.0 _2023 rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Gelænder Type A v 1.0 _2025 rev 2.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Gelænder Type A v 1.0 _2025 rev 2.xlsx" />
    <None Remove="Model\Projektering tab\Beregningsark\Gelænder Type X_v 1.0_2023 rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\LobrepEC_190701 rev 09012023.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\LobrepEC_190701 rev 17012025.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Overslag på reaktioner V03-11-2025.xlsx" />
    <None Remove="Model\Projektering tab\Beregningsark\Regneark gelænder Type A med balusterben _v 1.0_2023_rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Regneark gelænder Type A uden ben _v_ 1.0_2023_rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Regneark gelænder Type A v 1.0 _2023 rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Regneark gelænder Type A v 1.0 _2023 rev 0.xlsx" />
    <None Remove="Model\Projektering tab\Beregningsark\Regneark gelænder Type X_v 1.0_2023 rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\reposEC_v2010141 rev 09012023.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\reposEC_v2010141 rev 17012025.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Rytmisk_personlast_bef.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Svingløb_v28-10-2022.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Type A med balusterben _v 1.0_2023_rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Type A uden ben _v_ 1.0_2023_rev 0.xlsm" />
    <None Remove="Model\Projektering tab\Beregningsark\Vibrationskomfort_ganglast_bef.xlsm" />
    <None Remove="Model\Projektering tab\Tjekliste.docx" />
    <None Remove="Model\Repos_Doc_Template - Deploy.dsc" />
    <None Remove="Model\Repos_Doc_Template.dsc" />
    <None Remove="UserControls\ArrowDown.png" />
    <None Remove="View\Icons\add_icon.png" />
    <None Remove="View\Icons\delete_icon.png" />
    <None Remove="View\Icons\delete_icon2.png" />
    <None Remove="View\Icons\delete_icon2_disabled.png" />
    <None Remove="View\Icons\delete_icon2_hover.png" />
    <None Remove="View\Icons\excel_icon.png" />
    <None Remove="View\Icons\FEM-Design_icon.png" />
    <None Remove="View\Icons\folder_icon.png" />
    <None Remove="View\Icons\pdf_icon.png" />
    <None Remove="View\Icons\question_mark_icon.png" />
    <None Remove="View\Icons\switch_icon.png" />
    <None Remove="View\Icons\switch_icon_disabled.png" />
    <None Remove="View\Icons\switch_icon_hover.png" />
    <None Remove="View\Icons\word_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="Microsoft.Office.Interop.Excel">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>9</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>00020813-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Model\FEM-Design tab\cfg_Agressiv.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\FEM-Design tab\cfg_EkstraAgressiv.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\FEM-Design tab\cfg_Standard.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\FEM-Design tab\Doc_template_NoSnowLoad.dsc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\FEM-Design tab\Doc_template_SnowLoad.dsc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\FEM-Design tab\Doc_Template - Deploy.dsc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Gelænder Type A v 1.0 _2023 rev 0.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Gelænder Type A v 1.0 _2025 rev 2.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Gelænder Type X_v 1.0_2023 rev 0.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\LobrepEC_190701 rev 17012025.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Overslag på reaktioner V03-11-2025.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\reposEC_v2010141 rev 17012025.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Rytmisk_personlast_bef.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Svingløb_v28-10-2022.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Type A med balusterben _v 1.0_2023_rev 0.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Type A uden ben _v_ 1.0_2023_rev 0.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Beregningsark\Vibrationskomfort_ganglast_bef.xlsm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Model\Projektering tab\Tjekliste.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="stairs_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FemDesign.Core" Version="23.7.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\FCM_logo.png" />
    <Resource Include="Images\FCM_logo_og_agf.png" />
    <Resource Include="Images\img_femdesign.png" />
    <Resource Include="Images\img_home.png" />
    <Resource Include="Images\img_projektering.png" />
    <Resource Include="Images\img_testpage.png" />
    <Resource Include="Images\minimize_def.png" />
    <Resource Include="Images\minimize_mo.png" />
    <Resource Include="Images\shutdown_def.png" />
    <Resource Include="Images\shutdown_mo.png" />
    <Resource Include="UserControls\ArrowDown.png" />
    <Resource Include="View\Icons\add_icon.png" />
    <Resource Include="View\Icons\delete_icon.png" />
    <Resource Include="View\Icons\delete_icon2.png" />
    <Resource Include="View\Icons\delete_icon2_disabled.png" />
    <Resource Include="View\Icons\delete_icon2_hover.png" />
    <Resource Include="View\Icons\excel_icon.png" />
    <Resource Include="View\Icons\FEM-Design_icon.png" />
    <Resource Include="View\Icons\folder_icon.png" />
    <Resource Include="View\Icons\pdf_icon.png" />
    <Resource Include="View\Icons\question_mark_icon.png" />
    <Resource Include="View\Icons\switch_icon.png" />
    <Resource Include="View\Icons\switch_icon_disabled.png" />
    <Resource Include="View\Icons\switch_icon_hover.png" />
    <Resource Include="View\Icons\word_icon.png" />
  </ItemGroup>

</Project>
